# Generated by Django 4.1.7 on 2023-03-09 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='staff',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
